config/routes.rb
class ActionDispatch::Routing::Mapper

  def draw(routes_name)
    instance_eval(
      File.read(
        Rails.root.join("config/routes/#{routes_name}.rb")
      )
    )
  end

end

Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

    devise_scope :user do
      get "/login" => "devise/sessions#new", as: :login
      get "/logout" => "sessions#destroy", :as => :logout
      get "/signup" => "registrations#new", :as => :signup
      scope "my" do
        get "profile", to: "registrations#edit"
        put "profile/update", to: "registrations#update"
        get "password/edit", to: "registrations#edit_password"
        put "password/update", to: "registrations#update_password"
      end
    end

    unauthenticated do
      get "/logout" => redirect("/")
    end

    authenticate :user, ->(u) { u.super_admin? } do
      get "/delayed_job" => DelayedJobWeb, :anchor => false
      put "/delayed_job" => DelayedJobWeb, :anchor => false
      post "/delayed_job" => DelayedJobWeb, :anchor => false

      ActiveAdmin.routes(self)
      namespace :superadmin do
        root to: "users#index"
        resources :users
      end

    end

    get "pages/about"
    get "pages/contact_us"
    resources :contacts, only: [:create]

    authenticated :user do
      get "/pages" => "pages#index", as: :pages
    end

    unauthenticated do
      as :user do
        root :to => "devise/sessions#new", as: :unauthenticated_root
      end
    end

    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        devise_scope :user do
          post "login" => "sessions#create", as: "login"
        end

        resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
      end
    end

    root "home#index"

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, :rememberable

  mount_uploader :profile_image, ProfileImageUploader

  before_save :ensure_authentication_token_is_present

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  def name
    [first_name, last_name].join(" ").strip
  end

  def super_admin?
    role == "super_admin"
  end

  def as_json( options = {} )
    new_options = options.merge({ only: [:email, :first_name, :last_name, :current_sign_in_at] })

    super new_options
  end

  private

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later(queue: "devise_email")
  end

  def ensure_authentication_token_is_present
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  skip_before_action :authenticate_user!, only: [:create]
  skip_before_action :authenticate_user_using_x_auth_token, only: [:create]

  def show
    @user = User.find_by(email: params[:id])

    if @user
      render json: @user
    else
      respond_with_error "User with email #{params[:id]} not found.", :not_found
    end
  end

  def create
    @user = User.create user_params

    if @user.valid?
      render json: @user
    else
      render json: { error: @user.errors.full_messages.to_sentence }, status: 422
    end
  end

  def update
    @user = User.find_by(email: params[:id])

    if @user.blank?
      respond_with_error "User with email #{params[:id]} not found.", :not_found

    elsif @user.update_attributes(user_params)
      render json: @user

    else
      render json: { error: @user.errors.full_messages.to_sentence }, status: 422
    end
  end

  def destroy
    @user = User.find_by(email: params[:id])

    if @user.blank?
      respond_with_error "User with email #{params[:id]} not found.", :not_found

    elsif @user.destroy
      render json: @user

    else
      render json: { error: @user.errors.full_messages.to_sentence }, status: 422
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/controllers/superadmin/base_controller.rb
class Superadmin::BaseController < ApplicationController

  before_action :ensure_current_user_is_superadmin!

  layout "superadmin"

end

app/controllers/superadmin/users_controller.rb
class Superadmin::UsersController < Superadmin::BaseController

  before_action :load_user, only: [:edit, :update]

  def index
    @users = User.order("id desc")
  end

  def edit
    @user_name = @user.name

    render partial: "edit_modal"
  end

  def update
    @user_name = @user.name
    @user.update(user_params)
    if @user.valid?
      flash[:notice] = "Information for user #{@user.name} successfully updated!"
      render json: { redirect_to: superadmin_users_path }
    else
      render json: { modal_content: render_to_string(partial: "edit_modal") }
    end
  end

  private

  def load_user
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :profile_image, :email)
  end

end

app/views/superadmin/users/_edit_modal.html.haml
= content_for(:modal_title) do
  Edit #{@user_name.to_s.humanize}

= content_for(:modal_body) do
  .row{style: "padding-top: 10px;"}
    = simple_form_for(@user, url: superadmin_user_path(@user),                                     |
                             method: :patch,                                                       |
                             html: { method: :put, class: 'bootstrap-center-form-medium' }) do |f| |
      .form-controls
        = f.input :email, required: true,                       |
                          autofocus: true,                      |
                          input_html: { class: 'form-control' } |
        = f.input :first_name, required: true, input_html: { class: 'form-control' }
        = f.input :last_name, required: true, input_html: { class: 'form-control' }
        = f.input :profile_image, as: :file
      .form-buttons
        = f.button :submit, "Update", class: 'btn btn-primary'


= render "shared/modal"

app/views/superadmin/users/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Email
      %th Last signed in
      %th
  - @users.each do |user|
    %tr
      %td
        = user.name
      %td
        = user.email
      %td
        = user.last_sign_in_at
      %td
        = link_to 'Edit', "#", data: { url: edit_superadmin_user_path(user), behavior: 'display-in-modal' }